version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: newshub-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - newshub_data:/var/lib/postgresql/data
    networks:
      - newshub-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: newshub-redis
    ports:
      - "6379:6379"
    networks:
      - newshub-net

  app:
    build: .
    container_name: newshub-app
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - newshub-net

volumes:
  newshub_data:

networks:
  newshub-net:
    driver: bridge